### ISSUE TITLE
Return error value in not-Natural branch

### ISSUE THREAD

**Issue by DmitrTRC** [posdima/C_course_1#10]
https://github.com/posdima/C_course_1/blob/3d1eed09d6b5c8143f1005cd0ebb2ca14cab260c/Homework_3_1/main.cpp#L15

* Return  Error value instead 0

**Comment by posdima** [comment]
Thanks!
I should change it to "return -1", of course

**Comment by posdima** [comment]
Done

**Comment by DmitrTRC** [comment]
Никак нет!  Система принимает и понимает именно как Unsigned Поэтому 1 .

**Comment by DmitrTRC** [comment]
1 - Catchall for general errors
2 - Misuse of shell builtins (according to Bash documentation)
126 - Command invoked cannot execute
127 - “command not found”
128 - Invalid argument to exit
128+n - Fatal error signal “n”
130 - Script terminated by Control-C
255\* - Exit status out of range

**Comment by DmitrTRC** [comment]
Ошибку то верни! Только корректную.

**Comment by posdima** [comment]
https://github.com/posdima/C_course_1/blob/main/Homework_3_1/main.cpp

Вот здесь прописал return 1
