### ISSUE TITLE
Функция должна только вернуть значение.убрать вывод результата.

### ISSUE THREAD

**Issue by DmitrTRC** [posdima/C_course_1#11]
https://github.com/posdima/C_course_1/blob/3d1eed09d6b5c8143f1005cd0ebb2ca14cab260c/Homework_3_2/least_divisor.cpp#L15

**Comment by posdima** [comment]
Изначально не хотел ставить, но тогда выводит обе строки:

The least common divisor is: 5

The least common divisor is 1

**Comment by DmitrTRC** [comment]
Даю наводку - избавься от второго return  - он только усложняет логику.

**Comment by posdima** [comment]
Спасибо! Подправил
