### ISSUE TITLE
Need Fix! The program works incorrectly!

### ISSUE THREAD

**Issue by DmitrTRC** [posdima/C_course_1#12]
https://github.com/posdima/C_course_1/blob/3d1eed09d6b5c8143f1005cd0ebb2ca14cab260c/Homework_3_3/change_digits.cpp#L4
The program works incorrectly!

* Try out 1000

**Comment by posdima** [comment]
Really don't know how to code so universal program

**Comment by DmitrTRC** [comment]
Ну есть много способов. Решение в лоб - просто разложи в массив и пересобери число.

**Comment by posdima** [comment]
Сделал. Работает.
