### ISSUE TITLE
Советую разделить проекты.

### ISSUE THREAD

**Issue by DmitrTRC** [posdima/C_course_1#14]
Hi! Молодец , что продолжаешь! 

Не запихивай все проекты в один репозиторий.
Тяжело и поддерживать и падать будет - забудешь в каком что поменял, для коллаборантов и вообще PR - просто один геморрой! Ну ладно когда задачи курса.. Но когда уже абсолютно новый - точно не стоит!

**Comment by posdima** [comment]
Привет!
Да, спасибо за совет. Так и сделаю - создам новый репозиторий для данной игры при следующих пушах👍🏻
