### ISSUE TITLE
Use Class Constructor instead

### ISSUE THREAD

**Issue by DmitrTRC** [posdima/C_course_1#15]
https://github.com/posdima/C_course_1/blob/58f4298d55329481c08a4d6160e28b1219cc0855/Arkanoid/Board.cpp#L4

A much better way - is just to implement a new class and make it a constructor

**Comment by posdima** [comment]
Thanks, I'm sure that it's much better, but now I just want to train my C coding and try to do this game before we will start next C++ level in which we will use it. Now I don't know about classes and constructors a lot for use it in coding😃
