### ISSUE TITLE
Check for loop conditions

### ISSUE THREAD

**Issue by DmitrTRC** [posdima/C_course_1#4]
https://github.com/posdima/C_course_1/blob/d280cb4bf9b377e9b10014de4d214f8a950954bd/Homework_3_4/main.cpp#L12

* Better to use while-loop instead of for-loop in such cases.

**Comment by DmitrTRC** [comment]
### Still wrong for-loop logic! 
* Endless loop warning.

**Comment by posdima** [comment]
I don't understand where is Endless loop. 
Loop is working while decimal number more than zero, than it ends.

The clear last version:

https://github.com/posdima/C_course_1/blob/main/Homework_3_4/main.cpp
