### ISSUE TITLE
Better way to use constant variable instead of #define ( No Type checking ) 

### ISSUE THREAD

**Issue by DmitrTRC** [posdima/C_course_1#5]
https://github.com/posdima/C_course_1/blob/4cce7787e1ca5dc0a791d0ea5127b243af36f398/Homework_3_5/main.cpp#L5

**Comment by posdima** [comment]
I've just taken #define like a macro for preprocessoring and use it only for testing variable conditions.

**Comment by DmitrTRC** [comment]
Неважно. Это плохой подход. Не привыкай!

**Comment by posdima** [comment]
Убрал. Переписал немного прогу
