### ISSUE TITLE
This is a BOOLEAN Type function . Return -> bool instead of int

### ISSUE THREAD

**Issue by DmitrTRC** [posdima/C_course_1#6]
https://github.com/posdima/C_course_1/blob/4cce7787e1ca5dc0a791d0ea5127b243af36f398/Homework_3_5/main.cpp#L8

**Comment by posdima** [comment]
Yes, but it's only for test and I think it's ok because I just need true or false while variable is tested

**Comment by DmitrTRC** [comment]
Рано или поздно приведет  к ошибкам. Используй для валидаторов тип bool

**Comment by posdima** [comment]
Убрал. Переписал немного прогу
