### ISSUE TITLE
Try x = 0.99 

### ISSUE THREAD

**Issue by DmitrTRC** [posdima/C_course_1#7]
Let x  = 0.99
The first member of the series is x: SUM = 0.99
The second member of the series is x1 =  (pow ( x, 3 ) /  ( 2* 3 ) = 0.1617165, SUM = 0.99 + x1 = 1.1517165
The third member of the series is x2 = ( 1 * 3 * pow ( x, 5 )) / ( 2 * 4 *5 ) = 0.07132425,  SUM =  1.1517165 + x2 = 1.223041

And this is your answer :

Enter number x, which is more than 0.05 and less than 1: 0.99
Sum is: 1.177590

**Comment by posdima** [comment]
Thanks, I will check it with debuger more clearly.

**Comment by DmitrTRC** [comment]
Still wrong result!

**Comment by posdima** [comment]
Reviewed code. Really can't find mistake.

**Comment by DmitrTRC** [comment]
Используй Debugger. или просто печатай контрольные значения на каждой итерации

**Comment by DmitrTRC** [comment]
И смотри - тесты должны тебе же для проверки помогать, а ты де-факто просто подогнал ИХ под вывод.
Посчитай пару значений вручную и сравни.

**Comment by posdima** [comment]
Поправил. Проверил через отладчик. Вроде нормальные теперь цифры выдает
