### ISSUE TITLE
Замечания Homework_3_3

### ISSUE THREAD

**Issue by imirrori** [posdima/C_course_1#8]
Кажется тут не хватает return
https://github.com/posdima/C_course_1/blob/ac9b17084da7486b3cb0651bd725c34ed10fa687/Homework_3_3/main.cpp#L14

Тут нужно использовать инициализацию значения и переменную делать const
https://github.com/posdima/C_course_1/blob/ac9b17084da7486b3cb0651bd725c34ed10fa687/Homework_3_3/main.cpp#L17

**Comment by posdima** [comment]
Переписал код совершенно по-другому
